

server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka   #是一个默认的注册中心地址。配置该选项后，可以在服务中心进行注册。
    fetch-registry: false   #检索服务选项，当设置为True(默认值)时，会进行服务检索,注册中心不负责检索服务。
    register-with-eureka: false  #服务注册中心也会将自己作为客户端来尝试注册自己,为true（默认）时自动生效

security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
